version: '3.8'

services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - weaviate

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
